### PR TITLE
Add Java ND4J (Moore-Penrose) Pseudo Inverse (left/right) Implementation

### PR DESCRIPTION
**Pull request by slang03**
## What changes were proposed in this pull request?

Add methods to compute the left and right pseudo-inverse by simple
matrix multiplications directly in ND4J according to
https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Definition

The method makes use of `InvertMatrix.invert(..)` which at the moment
uses apache commons math so this is not a 100% ND4J based implementation but
as soon as someone implements an invert method in ND4J using Blas this
should be fine.

See also: #2858

## How was this patch tested?

Tests for left and right inverse are added in TestInvertMatrices.java
for working and nonworking (singular matrix) cases.

### CODE REVIEW

**Comment by saudet** [comment]
Is this the same as pull #2861?

**Comment by slang03** [comment]
No, #2861 relies on apache commons math's `QRDecomposition` (See also [wiki](https://en.wikipedia.org/wiki/QR_decomposition#Using_for_solution_to_linear_inverse_problems)) while this pull request offers the direct closed-form solutions to right/left pseudo-inverses.

**Comment by saudet** [comment]
Ah, I see, what do you think @tteofili?

**Comment by tteofili** [comment]
sounds good to me to use this pseudo inverse impl because it only relies on commons-math for the inverse calculation, so as soon as inverse is fixed with a pure nd4j impl, the pseudo inverse calculation won't depend on commons-math anymore either.

**Comment by slang03** [comment]
I'm not sure but it might be worth having both implementations. I'm not too deep into the actual math there, but is there a case where you cannot compute the pseudo matrix via the closed form solution while it is possible using a decomposition method? The closed form solution requires the input matrix to have either full row rank (right pseudo-inverse) or full column rank (left pseudo-inverse). The decomposition methods require the decomposed matrices to be non-singular as they usually use some components of the decomposed matrix and invert them which results in the pseudo-inverse for the input matrix. Is there a situation in which the input matrix does not have full rank but the decomposed matrices are not singular? @tteofili

**Comment by saudet** [comment]
Ok, let's merge both for now and keep on working on this :) We'll need to add a test for `pinvert()` too...

Thanks for the contributions guys!

**Pull request merged**
