### PR TITLE
tests need lombok

### PR DESCRIPTION
**Pull request by hvesalai**
## What changes were proposed in this pull request?

Add the required lombok dependency to tests

## How was this patch tested?

By running the tests and observing that they didn't compile without this

### CODE REVIEW

**Comment by AlexDBlack** [comment]
I'm pretty sure this is necessary? I can run the tests via both intellij and maven on master (i.e., adding this dependency isn't required) - and yes, I just re-checked. So I'm closing this unless it can be demonstrated that it's actually required for tests to run.

**Comment by hvesalai** [comment]
@AlexDBlack I think I demonstrated that this is required with mvn `3.5.3`. When you tried, did you have a fresh clone from github to rule out any interference from your earlier builds?

If you want to give me the mvn command to run the tests with, I can run an upload the resulting build logs. All I know is that without this, the tests would not even compile for me. And I think that is natural because the dependency is declared as `provided` in `nd4j-api`.

**Comment by hvesalai** [comment]
The command I was running was both `mvn -Dtest=Nd4jTestsC test -pl :nd4j-tests` on the top level and `mvn -Dtest=Nd4jTestsC test` in the `nd4j-tests` directory. Both started working after this change.

**Comment by saudet** [comment]
@hvesalai You must be doing something wrong, it works just fine for me as well with Maven 3.5.2.

The commands you are using though don't actually do anything. Did you mean `mvn -Dtest=Nd4jTestsC test -Ptestresources` in the `nd4j-native` directory?

**Comment by hvesalai** [comment]
@saudet No, I used the command I provided. The thing I failed to mention was that I edited the nd4j-tests pom.xml to enabled the tests as instructed by @treo 

Anyway, I think I found the reason for this behavior. I was working on top of commit 4cdd4fab4e9434ed9fecd90862d50962e58216c5, so I was missing commit a0e5db60, which also modified the lombok dependencies.

I confirm that this patch is not needed and I can also run the tests without it on top of latest master. I'm sorry for all the trouble.

**Comment by AlexDBlack** [comment]
@hvesalai no worries, not a big deal - thanks for clarifying.

**Pull request closed without merging**
