### PR TITLE
Manually revert PR #2722 and add deprecations/checks

### PR DESCRIPTION
**Pull request by AlexDBlack**
See: https://github.com/deeplearning4j/nd4j/pull/2722#issuecomment-373933362

Github won't let me automatically revert the PR, so I'm doing it manually.
Also adding check + deprecation.

### CODE REVIEW

**Comment by AlexDBlack** [comment]
@raver119 ok, I'll merge this and open an issue to separately handle the removal of the setters/enum etc properly.

**Comment by raver119** [comment]
cool thanks!

**Comment by enragedginger** [comment]
LGTM. Thank you!

**Comment by AlexDBlack** [comment]
@enragedginger np, and thanks for flagging the original issue

**Pull request merged**
