### PR TITLE
Added basic preprocessors for stdscaler and minmax

### PR DESCRIPTION
**Pull request by eraly**
Preprocessor tests and code.

### CODE REVIEW

**Comment by agibsonccc** [comment]
+1. We need more of these.

**Comment by AlexDBlack** [comment]
What's the status here? Would be good to get this done and into the next release.

**Comment by agibsonccc** [comment]
It looks done. Not sure what else is missing.

**Comment by eraly** [comment]
Tests are not complete.

**Comment by eraly** [comment]
Merging. Tests passing.

**Pull request merged**
