### PR TITLE
Minor printing improvements esp if column vector

### PR DESCRIPTION
**Pull request by eraly**
## What changes were proposed in this pull request?
https://github.com/deeplearning4j/nd4j/issues/1929

## How was this patch tested?
Unit test

Please review
https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md before opening a pull request.

### CODE REVIEW

**Comment by agibsonccc** [comment]
Got a sample of the output?

**Comment by eraly** [comment]
This is 5x1:

[ 1.00, 
  2.00, 
  3.00, 
  4.00, 
  5.00]

This is 2x4x1:

[[ 1.00, 
  3.00, 
  5.00, 
  7.00],  

 [ 2.00, 
  4.00, 
  6.00, 
  8.00]]

**Comment by AlexDBlack** [comment]
Does this mean that a [1000,1] will print as 1000 lines, instead of the current 1 line? If so, I'm not sure how much I like that...
an alternative might be to use a different delimiter, like ";"?
i.e., a 5x1 would print as ```[1; 2; 3; 4; 5]```

**Comment by agibsonccc** [comment]
That's actually more of what people expect though. I would be ok with this.
We can control the truncation remember.

**Comment by eraly** [comment]
@AlexDBlack Yes. Currently it will print 1000 lines.
I can make some changes if we want to truncate the printed string.
Say if it's bigger than say 150 (?) we just do "..." and the last row?

**Comment by AlexDBlack** [comment]
Limiting here makes sense, and first N, ..., last is good.
As for the specific limit - we can make it reasonably generous, maybe 500 or so?

**Comment by eraly** [comment]
So I had this nagging feeling this was going to break something that I had written a long time ago and I couldn't put my finger on it. And now I know what:

https://github.com/deeplearning4j/nd4j/blob/88f62abd5b43489942f4394bf90f901de5b09a17/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L2401

**Comment by eraly** [comment]
I need to make sure that what I am doing here doesn't break the NdArrayJSONReader and NdArrayJSONWriter or the readTxt/writeTxt functionality in Nd4j.

The tests for them don't cover the column vector edge case.  We do want to support the JSON reader/writer functionality, right? It might be correct but it's pretty brittle (I wrote it a long time ago so you can blame me) and there is plenty of cleaning up I can do there...

**Comment by AlexDBlack** [comment]
Quick thought: I wonder if we can leverage (or share code with) some of the existing Jackson serializers for JSON?

**Comment by eraly** [comment]
I will look into leveraging what we have in jackson for this.

**Comment by eraly** [comment]
I will get back to this after the use case disco

**Comment by huitseeker** [comment]
@eraly Any news on getting back to this one?

**Comment by eraly** [comment]
Hang up was what to do with the NdArrayJSONReader and NdArrayJSONWriter. Tests for these are ignored in current master and I think in the past release as well. I am voting to deprecate it. I don't see it being used anywhere.

**Comment by huitseeker** [comment]
@eraly I <3 deprecations! Go ahead!

**Comment by agibsonccc** [comment]
@eraly we should probably just move forward with deletions here.  We're doing a major version bump anyways.

**Comment by eraly** [comment]
Overrode this branch by mistake TF import stuff :( Will reopen

**Pull request closed without merging**
