### PR TITLE
get rid of nd4j fields

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Get rid of BaseNDArray Fields that aren't cached.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

Please review
https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md before opening a pull request.

### CODE REVIEW

**Comment by turambar** [comment]
Getting a build error on redhat linux in the `nd4j-native` module. Dunno if it's just me or a potential problem. Interestingly, builds fine on Mac OS X. Here's the full error from maven using the `-e` option:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project nd4j-native: Compilation failure
[ERROR] /home/dkx13490/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java:[62,15] org.nd4j.nativeblas.Nd4jCpu.NativeOps is not abstract and does not override abstract method sortCooIndicesHalf(org.bytedeco.javacpp.PointerPointer,org.bytedeco.javacpp.IntPointer,org.bytedeco.javacpp.ShortPointer,long,int) in org.nd4j.nativeblas.NativeOps
[ERROR]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project nd4j-native: Compilation failure
/home/dkx13490/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java:[62,15] org.nd4j.nativeblas.Nd4jCpu.NativeOps is not abstract and does not override abstract method sortCooIndicesHalf(org.bytedeco.javacpp.PointerPointer,org.bytedeco.javacpp.IntPointer,org.bytedeco.javacpp.ShortPointer,long,int) in org.nd4j.nativeblas.NativeOps

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/dkx13490/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java:[62,15] org.nd4j.nativeblas.Nd4jCpu.NativeOps is not abstract and does not override abstract method sortCooIndicesHalf(org.bytedeco.javacpp.PointerPointer,org.bytedeco.javacpp.IntPointer,org.bytedeco.javacpp.ShortPointer,long,int) in org.nd4j.nativeblas.NativeOps

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:972)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nd4j-native
```

**Comment by turambar** [comment]
There appears to be a handful of abstract methods in `org.nd4j.nativeblas.NativeOps` that are not implemented by `org.nd4j.nativeblas.Nd4jCpu.NativeOps`.

**Comment by turambar** [comment]
Update: this is occurring on `master` as well as the `nd4jfields` branch.

**Comment by raver119** [comment]
Have you pulled latest libnd4j master and successfully rebuilt it? That's the only thing i could think of right now. Abstract method error you've posted - makes no sense, method exists.

**Comment by turambar** [comment]
Yes. But I'll try again. :)

**Comment by agibsonccc** [comment]
@turambar that is definitely javacpp related. It's also javacpp related. I have to ignore this.

**Comment by saudet** [comment]
@turambar It is still happening? This can only happen with libnd4j and nd4j are out of sync...

**Comment by turambar** [comment]
Nope, everything builds fine.

**Pull request merged**
