### PR TITLE
SELU

### PR DESCRIPTION
**Pull request by raver119**
SELU, SELUDerivative + ActivationSELU wrappers on java side

As requested here: https://github.com/deeplearning4j/nd4j/issues/1878

### CODE REVIEW

**Comment by maxpumperla** [comment]
@raver119 nice commit message :)

Not sure if I understand this correctly, but for now this seems to just be `tan` and derivative `1/cos^2`, not the scaled exponential with the two weird constants. Still WIP?

**Comment by raver119** [comment]
Nah, it's just wrapper for libnd4j part, activation is implemented in native code, and tan/derivative is just copy/paste issue, java op isn't used... Should fix that though, thanks for highlighting

**Comment by raver119** [comment]
https://github.com/deeplearning4j/libnd4j/pull/401

**Comment by maxpumperla** [comment]
interesting, thanks for clarifying this. otherwise lgtm!

**Pull request merged**
