### PR TITLE
Added sample LAPACK for cpu & for cuda 

### PR DESCRIPTION
**Pull request by rcorbish**
Please review this request to see whether it is a good approach to adding in LAPACK. I used javacpp-presets to access the native libs.

### CODE REVIEW

**Comment by saudet** [comment]
I've released stuff on the Maven Central Repository, so the following should work now:
```xml
    <properties>
        <openblas.version>0.2.19</openblas.version>
        <javacpp-presets.version>1.2</javacpp-presets.version>
        <javacpp.version>1.2.5</javacpp.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>${javacpp.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>${openblas.version}-${javacpp-presets.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>${openblas.version}-${javacpp-presets.version}</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>${openblas.version}-${javacpp-presets.version}</version>
            <classifier>macosx-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>${openblas.version}-${javacpp-presets.version}</version>
            <classifier>windows-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>${openblas.version}-${javacpp-presets.version}</version>
            <classifier>linux-ppc64le</classifier>
        </dependency>
    </dependencies>
```
All that is basically going to move to the platform artifacts in the next major release of JavaCPP later this month, but the effect is pretty much the same. Just a bit more verbose. Let me know if this doesn't work for some reason! Thanks

**Comment by saudet** [comment]
The same for CUDA works, as per
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-cuda/pom.xml

**Comment by saudet** [comment]
FYI, you're trying to do things the hard way. There is already a complete Java interface for cuSOLVER available in the JavaCPP Presets: https://github.com/bytedeco/javacpp-presets/blob/master/cuda/src/main/java/org/bytedeco/javacpp/cusolver.java

**Comment by saudet** [comment]
@rcorbish I've merged my pull request for BLAS. Could you resolve the conflicts by removing calls to libnd4j, removing duplicate dependencies on openblas and cuda presets, and other small things? Thanks!

**Comment by rcorbish** [comment]
Will do - I'll be able to start tonight (NY time)


________________________________

**Comment by saudet** [comment]
@rcorbish Thanks! There are still changes needed though. Let us know when you have some time to work on this

**Comment by saudet** [comment]
Ok, I pushed the few necessary updates. @rcorbish Let me know if this looks alright and if you're ready to merge! Thanks

**Comment by saudet** [comment]
It shouldn't affect any of the existing functionality, so I'll merge that before it diverges too much from master. @rcorbish Please send more pull requests to keep working on that! Thanks

**Comment by rcorbish** [comment]
Sorry - I was out for a while. PLease let me know what I need to do


________________________________

**Comment by saudet** [comment]
Depends, @agibsonccc anything in particular that we should work on first?

**Pull request merged**
