### PR TITLE
Syntax checking (the manual, safe version)

### PR DESCRIPTION
**Pull request by huitseeker**
Simplifies formatting plugins, fixes analogous of https://github.com/deeplearning4j/DataVec/issues/199 also present here.

Offers an `nd4j/contrib/maybeFormat.sh` that will tell you of syntax violations (if any) and ask you if you want to fix them, interactively.

### CODE REVIEW

**Comment by eraly** [comment]
What should I run on the command line? Do I need to make any modifications before running?

**Comment by huitseeker** [comment]
You can run `nd4j/contrib/maybeFormat.sh` to start formatting manually, but the formatting should be triggered by any `mvn` command triggering a phase after `generate-sources`. `mvn compile` will do for example.

**Comment by eraly** [comment]
Checked out huitseeker:syntax-enforcement-3 and ran
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-8.0,!org.nd4j:nd4j-cuda-8.0-platform,!org.nd4j:nd4j-tests'

https://gist.github.com/eraly/60548f2e4f0b2363bf0c2809025cc11d

**Comment by huitseeker** [comment]
- can you re-run with `mvn -e -X` ?
- the file sought after is obviously in the PR ( https://github.com/deeplearning4j/nd4j/pull/1695/commits/d425bb85a63d3d1dd868d59c3d50bcb37a14515b ) and the path in the gist is correct: 
`/Users/susaneraly/SKYMIND/nd4j/contrib/maybeFormat.sh`
- so it's very weird this error happens. Is the file there on your disk ? Are you sure your checkout happened OK ?

**Comment by eraly** [comment]
The file is on disk. 
https://gist.github.com/eraly/ab5798e0b7b46ba3a33607323977cbbb

**Comment by huitseeker** [comment]
That's amazing. Is it executable ? what does `stat contrib/maybeFormat` say ?

**Comment by eraly** [comment]
stat contrib/maybeFormat.sh 
16777220 6314455 -rwxr-xr-x 1 susaneraly staff 0 863 "Mar 12 11:24:24 2017" "Mar 12 09:36:40 2017" "Mar 12 09:36:40 2017" "Mar 12 09:36:40 2017" 4096 8 0 contrib/maybeFormat.sh

**Comment by huitseeker** [comment]
OK it is, so the only possibility is OSX has trouble with absolute paths. I've pushed a commit that uses a relative path, can you retry?

**Comment by eraly** [comment]
https://gist.github.com/eraly/d8bcff32b46310a15404038e7fc8eb81

**Comment by huitseeker** [comment]
So, this is frustrating, because the plugin's mojo checks it can find the executable path before it launches anything — that's also why it converts to an absolute path https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/ExecMojo.java#L685
The amazing stuff is that this error only happens when it forks and launches the command !?
https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/ExecMojo.java#L763

**Comment by huitseeker** [comment]
@eraly, is there a chance you'd manage to run anything (executable) with the exec-maven plugin ? Because it will take me a little while to reproduce a test on Mac and until then I'm at a loss as to the next thing to try.

**Comment by eraly** [comment]
k, will do and update.

**Comment by huitseeker** [comment]
This PR is fairly old and there hasn't been much activity on it. Closing, but please re-open if interest strikes.

**Pull request closed without merging**
