### PR TITLE
Log about initializeDevicesAndFunctions() potentially taking a while

### LINKED ISSUE #2715: CUDA runtime (ptx) compliation - detect when occuring, log message
With current snapshots, we apparently aren't building for all architectures. For other architectures, a compilation step is required. This can take a considerable amount of time (10+ minutes?).

Currently, this provides zero feedback to the user when this is occuring - it just looks like ND4J has frozen during initialization, which provides a very poor user experience.

### PR DESCRIPTION
**Pull request by saudet**
Fixes #2715 

## What changes were proposed in this pull request?

Add call to log.info() before call to initializeDevicesAndFunctions()

## How was this patch tested?

Tested manually: Message shows with nd4j-cuda backend, doesn't show with nd4j-native one.

### CODE REVIEW

**Comment by saudet** [comment]
Let's just add a note about that in https://deeplearning4j.org/snapshots then?

**Comment by AlexDBlack** [comment]
Well, again, it's bad UX... we already know people don't read docs - and even those that do won't necessarily remember. I'd rather we make it obvious/explicit/automatic as possible. I'm happy to implement the timer-based approach I mentioned, if you want.

**Comment by saudet** [comment]
But I don't like these ugly hacks :) They create additional bugs we don't need...

Well, since CUDA 9 can't reliably JIT compile libnd4j anymore (issue #2632) maybe this is a moot point?

**Comment by AlexDBlack** [comment]
@saudet you might be right about that... until we have JIT compilation occurring reliably - or (even better :)) we don't have any cases where JIT is required - warning won't do much to help.

**Pull request closed without merging**
