### PR TITLE
added ability to allow the user to set format of decimal with tests. 

### PR DESCRIPTION
**Pull request by claytantor**
I attempted to add a test but when I added the tests they would not get run as part of the test phase. I have tested the implementation using the following test:

```
    @Test
    public void testNd4jArrayString(){

        //2d array
        INDArray arr = Nd4j.create(new float[]{1f,20000000f,40.838383f,3f}, new int[]{2,2});

        //default
        String expected1 = "[[         1.00,20,000,000.00],\n" +
                " [        40.84,         3.00]]";
        String serializedData1 = new NDArrayStrings(",",2).format(arr);
        Assert.assertTrue(serializedData1.equals(expected1));

        //remove commas
        String expected2 = "[[       1.00,20000000.00],\n" +
                " [      40.84,       3.00]]";
        String serializedData2 = new NDArrayStrings(",",2,"######0").format(arr);
        Assert.assertTrue(serializedData2.equals(expected2));

    }
```

### CODE REVIEW

**Comment by claytantor** [comment]
I dont understand why this failed.

**Comment by claytantor** [comment]
If you tell me what I need to do to get this merged I will do it.

**Comment by AlexDBlack** [comment]
Sorry - looks like this just lost in the noise. Feel free to ping us on gitter (or PM me directly) in the future.
Tests failures are probably unrelated - we're seeing some other issues with Jenkins currently.

**Comment by eraly** [comment]
@claytantor The assertion was correct for 'c' order not 'f' order.

**Pull request merged**
