### PR TITLE
Variosu fixes

### PR DESCRIPTION
**Pull request by agibsonccc**
Param server fixes.

### CODE REVIEW

**Comment by gagatust** [comment]
`list.forEach((message) -> {`

Java8?

**Comment by raver119** [comment]
Nope, only in selected modules like this one. It relies on Aeron, which is java8.  More like exception from the general java7 rule.

**Comment by raver119** [comment]
I mean - we're 100% sure param server implementations will never be used on Android. So we don't care about android requirements here.

**Comment by gagatust** [comment]
OK

**Pull request merged**
