### PR TITLE
Native performance stuff

### PR DESCRIPTION
**Pull request by raver119**
***WIP; DO NOT MERGE; NOT INTENDED FOR 0.5.0***

* Various stuff for native performance investigation & improvements:
   - Operations chains for mGRID concatenation efforts estimation:
   - Stack traces for sub-optimal op params: strided/non-EWS access, bad TAD use cases
   - Various timing statistics
   - Additionally, special hook to check for NaN/Inf values in Op results
* Additional signatures for INDArray: lte/gte/ltei/gtei as boolean operations shortcuts
* Improved javadoc for Compare-and-Set & Compare-and-Replace
* Few other minor fixes for recently reported minor issues

### CODE REVIEW

**Comment by eraly** [comment]
start jenkins

**Comment by eraly** [comment]
Start Jenkins

**Comment by eraly** [comment]
Start Jenkins

**Comment by raver119** [comment]
Start jenkins

**Comment by eraly** [comment]
Start Jenkins

**Comment by raver119** [comment]
start jenkins

**Comment by raver119** [comment]
Skip jenkins

**Comment by agibsonccc** [comment]
Close this?

**Pull request merged**
