### PR TITLE
<WIP> Implement MultiNormalizerStandardize to normalize MultiDataSets

### PR DESCRIPTION
**Pull request by EdeMeijer**
This is a implementation of a normalizer preprocessor for MultiDataSets. I extracted most of the required functionality from NormalizerStandardize into a DistributionStats class that represents the mean and stddev of a set of data, so that it could be reused for the multi implementation.

Let me know what you think.

### CODE REVIEW

**Comment by EdeMeijer** [comment]
Okay, I think it's done.

**Comment by EdeMeijer** [comment]
Hmm I see that `org.nd4j.linalg.dataset.NormalizerStandardizeTest.testDifferentBatchSizes[0: backend(org.nd4j.linalg.jcublas.JCublasBackend)={1}]` fails on Jenkins. Could you give me some more details? I added that test, but it passed on my machine with native backend.

**Comment by saudet** [comment]
```
Error Message

expected:<1.7078299522399902> but was:<1.8708287477493286>

Stacktrace

java.lang.AssertionError: expected:<1.7078299522399902> but was:<1.8708287477493286>
	at org.nd4j.linalg.dataset.NormalizerStandardizeTest.testDifferentBatchSizes(NormalizerStandardizeTest.java:148)

Standard Output

o.n.l.BaseNd4jTest - Running org.nd4j.linalg.dataset.NormalizerStandardizeTest on backend org.nd4j.linalg.jcublas.JCublasBackend
o.n.l.BaseNd4jTest - Ending org.nd4j.linalg.dataset.NormalizerStandardizeTest
```
What are the specs of your machine?

**Comment by EdeMeijer** [comment]
Intel i7 quad core, 32GB ram, GTX 970 for CUDA, running on Ubuntu 16, using CUDA 8.0. I'll see if I can reproduce the issue by using the CUDA backend.

**Comment by EdeMeijer** [comment]
Hmm, the 1.87 looks suspiciously a lot like the bias corrected standard deviation... let me try something

**Comment by EdeMeijer** [comment]
Wow, okay, turns out that with the CUDA backend, you always get the bias corrected version back... I'll add an issue for that.

**Comment by EdeMeijer** [comment]
When https://github.com/deeplearning4j/nd4j/issues/1410 is fixed, we should try running the tests again

**Comment by eraly** [comment]
Nice! (reworking the classes) 
Let me look into why those few native tests are failing. And do some checks on 3d/4d datasets and masks.

**Comment by EdeMeijer** [comment]
Thanks :)

**Comment by EdeMeijer** [comment]
I merged the fix for the std issue on CUDA, and I also fixed the PreProcessor3D4DTest. The latter still assumed that sample variance was used instead of population variance.

**Comment by EdeMeijer** [comment]
Anything I can do to get this accepted?

**Comment by eraly** [comment]
@EdeMeijer Not really. I scanned it and it looks good. But since it's a major rewrite I want to give it more than a scan. Also, there are a couple of corner cases the current tests are not hitting so I will probably add those in as well. Probably later this week.

**Comment by eraly** [comment]
@EdeMeijer Can you resolve the merge conflicts?

**Comment by EdeMeijer** [comment]
Awesome, added you as collaborator.

**Comment by eraly** [comment]
@EdeMeijer 
Resolved conflict merged.
Added a test with the iterator vs non iterator case on the same data. 
Added a missing reset after the while loop:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/preprocessor/NormalizerStandardize.java#L93

Thanks for the restructuring. Definitely a lot cleaner now 😎

**Comment by EdeMeijer** [comment]
Great, thanks for merging!

**Pull request merged**
