### PR TITLE
added conversion from List<Float> and List<Double> to NDarray

### PR DESCRIPTION
**Pull request by borissmidt**
## What changes were proposed in this pull request?
#1991

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
I tested in manually using the scala repl. 
Please review
https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md before opening a pull request.

### CODE REVIEW

**Comment by saudet** [comment]
I think it would be clearer to overload the Nd4j.create() methods. What do you think @huitseeker?

**Comment by borissmidt** [comment]
@saudet i would really liked to do that, but because of the type erasure in java, f(List<A> x) is seen as the same as f(List<B> x). 
I'm not adept enough in java to solve this problem, so if you can assist i would be happy to help and probably learn something new :).

**Comment by saudet** [comment]
Ah yes that's an issue. :) LGTM then

**Comment by raver119** [comment]
Why not use single overload List<? extends Number>? We have fairly limited number of datatypes, and any Number should be converted appropriately?

**Comment by borissmidt** [comment]
Yes it seems like a good idea, How would i know if i have to call `Floats.toArray` or `Doubles.toArray` should i check the instance of the first element of the List?
```
public static INDArray createFloat(List<? extends Number>[] data) {
Number element = data.get(0)
if( element instanceof Float)
else if (element instanceof Double)
else if (element instanceof Long)
else if (element instanceof Integer)
}
        
```

**Comment by raver119** [comment]
No. You don't do that. Number has some methods, lint floatValue, doubleValue etc. So you just check for Nd4j.dataType(), and then use the same method (i.e. floatValue) on all elements to fill NDArray

**Comment by raver119** [comment]
I mean - it doesn't matters what exactly you have as Number. The only thing that matters is current datatype of Nd4j. Once you know that - you just use matching method of Number class. i.e. floatValue()

**Comment by borissmidt** [comment]
```
    public static DataBuffer createBuffer(double[] data) {
        DataBuffer ret;
        if (dataType() == DataBuffer.Type.DOUBLE)
            ret = Nd4j.getMemoryManager().getCurrentWorkspace() == null ? DATA_BUFFER_FACTORY_INSTANCE.createDouble(data) : DATA_BUFFER_FACTORY_INSTANCE.createDouble(data, Nd4j.getMemoryManager().getCurrentWorkspace());
        else if (dataType() == DataBuffer.Type.HALF)
            ret = Nd4j.getMemoryManager().getCurrentWorkspace() == null ? DATA_BUFFER_FACTORY_INSTANCE.createHalf(data) : DATA_BUFFER_FACTORY_INSTANCE.createHalf(ArrayUtil.toFloats(data), Nd4j.getMemoryManager().getCurrentWorkspace());
        else
            ret = Nd4j.getMemoryManager().getCurrentWorkspace() == null ? DATA_BUFFER_FACTORY_INSTANCE.createFloat(ArrayUtil.toFloats(data)) : DATA_BUFFER_FACTORY_INSTANCE.createFloat(ArrayUtil.toFloats(data), Nd4j.getMemoryManager().getCurrentWorkspace());
        logCreationIfNecessary(ret);
        return ret;
    }
```
So more like this function? So the usage of a halve/float/double array is an external setting?

**Comment by raver119** [comment]
nah. you want to create NDArray, not a buffer.

So something like this (beware, pseudo code!):
```
public static <T extends Number> INDArray create(List<T> list) {
   if (Nd4.dataType() == DataBuffer.Type.DOUBLE) { 
   double[] tempArray = new double[list.size()];
   int cnt = 0;
   for (T element: list) {
     tempArray[cnt++] = element.doubleValue();
  }
 return Nd4j.create(tempArray);
 } else {
 float[] tempArray = new float[list.size()];
   int cnt = 0;
   for (T element: list) {
     tempArray[cnt++] = element.floatValue();
  }
 return Nd4j.create(tempArray);
 }
}
```

So, in this case i'm always using double as temporary array, If current dataType is double. And using float temp array in all other cases.

Obviously, the same could be written without temp array and no code branching, just create empty NDArray of desired length, and call putScalar in loop.

**Comment by raver119** [comment]
Hm. Code turned out to be not a pseudo code :/

**Comment by borissmidt** [comment]
I will try to make the implementation with the putScalar in the loop but would it really be more efficient?

**Comment by raver119** [comment]
It might be a bit slower (neglectable though), but more memory-friendly.

**Comment by borissmidt** [comment]
I will add them this weekend, when i have the time to do it.

**Comment by huitseeker** [comment]
@borissmidt Any news for us? Do you think you'll have time to push this one over the line soon? It's so close!

**Comment by borissmidt** [comment]
I'm on vacation this is a why i am unable to do it now.

**Pull request merged**
