### PR TITLE
Fix: squid:S2095, Resources should be closed

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S2095 - “Resources should be closed”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S2095

 Please let me know if you have any questions.
Ayman Elkfrawy.

### CODE REVIEW

**Comment by AlexDBlack** [comment]
So this one isn't correct. finally block in Nd4j.readText should not be closing the input stream, then passing the closed stream to another method.

https://github.com/deeplearning4j/nd4j/pull/1069/files

**Comment by elkfrawy-df** [comment]
@AlexDBlack You are right, I think the best was just to put the return statement in the try body instead of reverting all of it.

**Comment by AlexDBlack** [comment]
@elkfrawy-df right, modifying it rather than reverting might have been easier.
Anyway, thanks for the PRs. Mind submitting a new PR for this with that fix?

**Comment by elkfrawy-df** [comment]
@AlexDBlack Sure, I will do so.

**Pull request merged**
