### PR TITLE
Added syev code

### PR DESCRIPTION
**Pull request by rcorbish**
## Issue 927 ( unsupported operation in Eigen values )

Added symmetric eigen -value and -vector code. Main library interfaces are unchanged. Just implemented eigen  for symmetric. CPU & CUDA 8.0 tested

## Test cases included

verified with matlab

### CODE REVIEW

**Comment by huitseeker** [comment]
Sorry, had to revert this to allow our builds to pass : https://github.com/deeplearning4j/nd4j/pull/1836
Feel free to reopen @rcorbish I'll be glad to merge this once it passes on Cuda 7.5
You can use the `./change-cuda-version.sh` script at the root of the repo to configure the repo for 7.5.

**Comment by saudet** [comment]
@rcorbish Looks like cusolverDnSsyevd and cusolverDnSsyevd isn't available at all on CUDA 7.5, so we'll need to do something like I've done for cusolverDnSorgqr and cusolverDnDorgqr here:
https://github.com/deeplearning4j/nd4j/pull/1762/files

**Comment by rcorbish** [comment]
OK - will take a look at this

**Comment by rcorbish** [comment]
OK - I think I have it. Need to test on 7.5. Should be OK by the weekend

**Comment by saudet** [comment]
Great! Looking forward to the patch :)

**Pull request merged**
