### PR TITLE
Adds numpy serialization and interop for nd4j

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?

Adds java part of numpy serialization.

## How was this patch tested?
1 unit test - needs more yet.
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

Please review
https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md before opening a pull request.

### CODE REVIEW

**Comment by saudet** [comment]
`*RawIndexer` shouldn't be imported because those won't be usable on Android and other JVMs where `Unsafe` isn't available. Why do you need them explicitly?

**Comment by agibsonccc** [comment]
I needed an indexer for creating a data buffer with nd4j. If you have an alternative I'm open to it.

**Comment by saudet** [comment]
Indexers are fine, but use say `IntIndexer.create(pointer)` without downcast.

**Comment by agibsonccc** [comment]
k added

**Pull request merged**
