### PR TITLE
#Fix for 2831

### PR DESCRIPTION
**Pull request by HDouss**
## What changes were proposed in this pull request?

Fixed the implementation.

## How was this patch tested?
It seems to me that nd4j-api does not have unit test. Tested locally by reading images with ImageLoader (scenario described in issue).

### CODE REVIEW

**Comment by agibsonccc** [comment]
@HDouss it does, at least ask before making assumptions that a widely used library doesn't have unit tests o_0. Please add your test to: https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j The reason we have the unit tests in here is because nd4j is a multi backend library. Different implementations should have the same results.

**Comment by HDouss** [comment]
@agibsonccc I did not ask because the method and the modifications are even too simple to test. By the way I did not find any unit test for any method of NDArrayUtil. Could you please point me to the test class, may be I missed something?

**Comment by agibsonccc** [comment]
@HDouss for this one I agree with you..a lot of the simpler classes/utilities that weren't meant for public consumption didn't have tests. if it's impacting someone though we generally ask folks to create tests both for our own maintenance as well as for adding simple cases. Feel free to create a simple test class there under the same package name. It can be used for future reference. Thanks for understanding!

**Comment by saudet** [comment]
Since this affects DataVec, just add the few lines of code you have in #2831 in some unit test there and that'll be alright :) Thanks

**Comment by HDouss** [comment]
@saudet I don't think it is a good idea. I added a unit test covering 2 methods of NDArrayUtil

**Pull request merged**
