### PR TITLE
Fix nd4j-cuda and nd4j-native for Gradle, sbt, and mvn test

### PR DESCRIPTION
**Pull request by saudet**
@crockpotveggies @AlexDBlack @raver119

### CODE REVIEW

**Comment by crockpotveggies** [comment]
Confirmed issue is fixed on Gradle. Thanks for getting that updated.

**Comment by crockpotveggies** [comment]
hmmm, might have spoken too soon. after system reboot I started getting this error, possibly the dep was cached?

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.bytedeco.javacpp.cuda.<clinit>(cuda.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.bytedeco.javacpp.cublas.<clinit>(cublas.java:12)
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.createNewCublasHandle(BasicContextPool.java:187)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.fillPoolWithResources(LimitedContextPool.java:88)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.<init>(LimitedContextPool.java:54)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.<init>(CudaZeroHandler.java:130)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:121)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:70)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<clinit>(BaseCudaDataBuffer.java:69)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:241)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1301)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1275)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:963)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3262)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3125)
	at ai.bernie.train.TrainerRunner.run(TrainerRunner.java:81)
	at ai.bernie.train.TrainerRunner.main(TrainerRunner.java:172)
Caused by: java.lang.UnsatisfiedLinkError: no cuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:752)
	... 22 more
```

**Comment by raver119** [comment]
For me nd4j-tests work just fine.

Examples etc were working even before this fix.

**Comment by crockpotveggies** [comment]
@raver119 it's a Gradle-specific issue. It will never occur on maven-based systems because Maven knows how to resolve classifiers, etc.

**Comment by saudet** [comment]
@crockpotveggies We still need to add all the stuff manually with Gradle when we don't use the `nd4j-cuda-platform` artifact, in this case the CUDA presets for your platform, that works as expected.

**Comment by crockpotveggies** [comment]
@saudet yea I was still appending the platform-specific classifier. So it sounds like I'll need to manually specify the deeplearning4j-cuda classifier as well?

**Comment by saudet** [comment]
You're probably missing this dependency (with your platform as classifier) which Gradle couldn't resolve:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-backend-impls/nd4j-cuda/pom.xml#L187

**Comment by crockpotveggies** [comment]
Yup that's the one I was thinking about. I can confirm that I was adding that to my build.gradle file earlier, then removed it. I wonder if it's being overridden somewhere. Will need to examine the dependency tree.

I ended up migrating from Gradle to Maven for this project. However, I think Gradle needs a plugin to help with these things (esp. w/ DL4J deps).

**Pull request merged**
